### ISSUE TITLE
Doesn't work on my M1

### ISSUE THREAD

**Issue by DA-Mena** [r1olo/spotify-adblock-macos#1]
- Download .app from Spotify, brew install show corruption error when finishing steps from README
- Used self signed cert with trust allowed for code signing
- Performed steps from README
- App can no longer open

**Comment by r1olo** [comment]
Try to open Spotify from terminal. If it says `Killed` it probably means the certs don't match or they're not trusted (macOS things..)
Make sure to rename the original library to `Chromium Embedded Framework.orig` because it's hardcoded in the fake lib. If it can't find the real library it crashes.
Also I see you mentioned brew, did you use Homebrew to install Spotify? Try to install it normally without it. Spotify's path is hardcoded too (`/Applications/Spotify.app`). You can change it before compiling.

**Comment by stanleyjzheng** [comment]
I'm having the same issue unfortunately. No message when opening Spotify from the terminal (it simply doesn't open), original library is named `Chromium Embedded Framework.orig`, and Spotify path is `/Applications/Spotify.app`.

**Comment by s0451** [comment]
I used to have this problem on the latest arm version of Spotify, but then I downgraded to the older Spotify arm beta version and that fixed the issue for me.

**Comment by stanleyjzheng** [comment]
Perhaps we should keep this issue open as using an old beta version of an application isn't a satisfactory solution. When adding `cef_is_rtl` to `spotiblock.c`, Spotify has a segmentation fault. 

Additionally, where did you download the Spotify ARM beta? I can't seem to find any source for it (even unofficially). Thanks.

**Comment by DA-Mena** [comment]
@stanleyjzheng https://download.scdn.co/SpotifyBetaARM64.dmg

**Comment by r1olo** [comment]
It appears the latest Spotify version requires the symbol `cef_is_rtl`.
It should be fixed now.
